server:
  #服务注册中心端口号
  port: 8887
eureka:
  instance:
    #服务注册中心实例的主机名
    hostname: virgo-register
    # 续约更新时间间隔（默认30秒）
    lease-renewal-interval-in-seconds: 1
    # 续约到期时间
    lease-expiration-duration-in-seconds: 30
  client:
    #是否向服务注册中心注册自己
    register-with-eureka: true
    #是否检索服务
    fetch-registry: true
    service-url:
      #服务注册中心的配置内容，指定服务注册中心的位置
      defaultZone: http://127.0.0.1:8888/eureka/,http://127.0.0.1:8889/eureka/
spring:
  application:
    name: virgo-register
